name: bouncy_listener
description: An easy to use, autocancellable debouncer. Can be used as a class or a one-off.
version: 1.0.0
repository: https://github.com/TheCarpetMerchant/bouncy_listener

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
